version: "3.9"
services:
  client: 
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: sleek-client
    ports:
      - 3000:3000
    volumes:
      - './client:/usr/app/client'
      - '/usr/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: sleek-server
    ports:
      - 8000:8000
    volumes:
      - './server:/usr/app/server'
      - '/usr/app/node_modules'
