version: "3.9"
services:
  client: 
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: sleek-client
    ports:
      - 3000:3000
    volumes:
      - './client:/usr/app'
      - '/usr/app/node_modules'
    environment:
      - REACT_APP_BACKEND_URL=/api
      - CHOKIDAR_USEPOLLING=true

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: sleek-server
    ports:
      - 8000:8000
    volumes:
      - './server:/usr/app'
      - '/usr/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true

  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:80
  #   restart: always
