version: "3.9"
services:
  client: 
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: sleek-client
    depends_on:
      - api
    ports:
      - 3000:3000
    volumes:
      - './client:/app'
      - '/app/node_modules'
    environment:
      # - REACT_APP_BACKEND_URL=/api
      - CHOKIDAR_USEPOLLING=true
    restart: always

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: sleek-api
    ports:
      - 8080:8080
    volumes:
      - './api:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always

  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 7777:80
  #   depends_on: 
  #     - api
  #     - client
  #   container_name: sleek-nginx
  #   restart: always
  #   networks:
  #     - sleek-net

# networks:
#   sleek-net:
#     driver: bridge