FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

COPY tsconfig.json ./

RUN npm install

RUN npm uninstall bcrypt

RUN npm install bcrypt

RUN rm -rf ./src/keys

COPY . .

EXPOSE 8080

CMD ["npm", "run", "start:dev"]
